name: Run Prediction Model

permissions:
  contents: write

on:
  schedule:
    - cron: '0 17 * * *'  # daily 19:00 Polish time
  workflow_dispatch:  # allow manual trigger

jobs:
  run-prediction:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_HOOK }}
    
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: ./  
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Fetch data
      - name: Get data
        run: python get_data.py

      # Step 5: Commit and push updated data
      - name: Commit and push weather data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add raw_data.csv
          git commit -m "Update raw data [skip ci]" || echo "No changes to commit"
          git push -f https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git

      # Step 6: Run prediction model (reads latest weather data)
      - name: Run prediction model
        run: python predict.py

      # Step 7: Commit and push prediction log
      - name: Commit and push prediction log
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add prediction_log.csv
          git commit -m "Update prediction log [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
